name: android_companion_for_wear_os_ereader
description: A Wear OS app for reading epub books on the go.
version: 1.0.0+10
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bookshelf_repository:
    path: ../packages/bookshelf_repository
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.15
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  assets:
    - assets/
    - shorebird.yaml
  uses-material-design: true
  generate: true

flutter_icons:
  # To regenerate:
  # dart run flutter_launcher_icons
  android: "launcher_icon"
  image_path: "assets/scriptureSpotterIcon.png"
  min_sdk_android: 30

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  color: "#fff380"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/scriptureSpotterIcon.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    image: assets/android12ScriptureSpotterIcon.png
    color: "#fff380"

    # App icon background color.
    #icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"
  ios: false
  web: false
