name: wear_os_bible_ereader
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  bloc: ^8.1.1
  bookshelf_repository:
    path: ../packages/bookshelf_repository
  epub_view: ^3.2.0
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  wear: ^1.1.0
  wearable_rotary: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
  generate: true
