name: wear_os_bible_ereader
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  bloc: ^8.1.1
  bookshelf_repository:
    path: ../packages/bookshelf_repository
  epub_view: ^3.2.0
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  meta: ^1.9.1
  wear: ^1.1.0
  wearable_rotary: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.15
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  assets:
    - assets/
    - shorebird.yaml
  uses-material-design: true
  generate: true

flutter_icons:
  # To regenerate:
  # dart run flutter_launcher_icons
  android: "launcher_icon"
  image_path: "assets/scriptureSpotterIcon.png"
  min_sdk_android: 30
